// <auto-generated />
namespace Web_Hutech_Gear.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class EditNews2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EditNews2));
        
        string IMigrationMetadata.Id
        {
            get { return "202304111537454_EditNews2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
