// <auto-generated />
namespace Web_Hutech_Gear.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
<<<<<<<< HEAD:Web_Hutech_Gear/Migrations/202305101416510_AddNewDatabase.Designer.cs
    public sealed partial class AddNewDatabase : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddNewDatabase));
        
        string IMigrationMetadata.Id
        {
            get { return "202305101416510_AddNewDatabase"; }
========
    public sealed partial class CreateDatabase : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreateDatabase));
        
        string IMigrationMetadata.Id
        {
            get { return "202305070735080_CreateDatabase"; }
>>>>>>>> master:Web_Hutech_Gear/Migrations/202305070735080_CreateDatabase.Designer.cs
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
