// <auto-generated />
namespace Web_Hutech_Gear.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
<<<<<<<< HEAD:Web_Hutech_Gear/Migrations/202305101512009_SubComment.Designer.cs
    public sealed partial class SubComment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SubComment));
        
        string IMigrationMetadata.Id
        {
            get { return "202305101512009_SubComment"; }
========
    public sealed partial class UpdataDatabase : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UpdataDatabase));
        
        string IMigrationMetadata.Id
        {
            get { return "202305070826334_UpdataDatabase"; }
>>>>>>>> master:Web_Hutech_Gear/Migrations/202305070826334_UpdataDatabase.Designer.cs
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
